version: '3'
services:
  ngword-db:
    image: postgres:11-alpine
    environment:
      PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      TZ: 'Asia/Tokyo'
    ports:
      - 5432:5432
