version: '3'
services:
  ngword-db:
    image: postgres:11-alpine
    environment:
      PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      TZ: 'Asia/Tokyo'
    ports:
      - 5432:5432

  mongo-taboo-code-db:
    image: mongo:4.4.1
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
